#!/bin/bash

printf "Beginning Build...\n"
mvn package
printf "Build successfull!\n"

printf "Now building docker image...\n"
docker build -t gig-java-api
docker run -d --rm gig-java-api
printf "Docker container is running\n\n"

printf "Adding Account '0000001' with a balance of €20000\n"
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"balance": "20000","accountNumber": "0000001"}' \
  localhost:8080/api/account/addOrUpdate

printf "\nAdding Account '0000002' with a balance of €10000\n"
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"balance": "10000","accountNumber": "0000002"}' \
  localhost:8080/api/account/addOrUpdate

printf "\nGetting list of accounts within database now...\n"
curl --request GET localhost:8080/api/account/getAll
printf

printf "\nMaking a bank transfer of €10000 from Account '0000002' to Account '0000001'\n"
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"sender": "0000002","receiver": "0000001","amount": "10000"}' \
  localhost:8080/api/account/bankTransfer
printf "Transfer completed!\n\n"

print "Retrieving Balance for Account Number '0000001'"
balance_0000001=(curl --request GET localhost:8080/api/account/balanceByAccountNo/0000001)
printf "Balance for Account Number '0000002' is €%s\n\n" balance_0000001

print "Retrieving Balance for Account Number '0000002'"
balance_0000002=$(curl --request GET localhost:8080/api/account/balanceByAccountNo/0000002)
printf "Balance for Account Number '0000002' is €%s\n" balance_0000002







